apiVersion: v1
kind: Namespace
metadata:
  name: vault
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: default
  namespace: vault
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["*"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: default
  namespace: vault
roleRef:
  kind: Role
  name: default
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: default
---
apiVersion: v1
kind: Pod
metadata:
  name: vault-init
  namespace: vault
spec:
  serviceAccount: default
  restartPolicy: Never
  containers:
  - name: vault-initializer
    image: ameypar/k8s-vault-initializer
    imagePullPolicy: Always
    args: ["-mode=standalone"]
    env:
      - name: VAULT_ADDR
        value: http://vault.vault.svc:8200
---
apiVersion: batch/v1
kind: Job
metadata:
  name: snapshot-test
  namespace: vault
spec:
  parallelism: 1
  completions: 1
  backoffLimit: 0
  manualSelector: false
  template:
    spec:
      containers:
        - name: vault-snapshot
          image: vault-snapshot
          env:
            - name: VAULT_ADDR
              value: http://vault.vault.svc:8200
            - name: VAULT_ROLE
              value: operator
      restartPolicy: Never
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      automountServiceAccountToken: true
