# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Build amd64 binary

on:
  workflow_call:
    inputs:
      upload-binary:
        required: false
        type: boolean
        default: false
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Build
      run: ./build.sh

    - name: Test
      run: go test -v ./...

    - uses: actions/upload-artifact@v3
      if: ${{ inputs.upload-binary }}
      with:
        name: vault-snapshot
        path: ./build/vault-snapshot
