name: "Create release"

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    name: "Build"
    uses: ./.github/workflows/go.yml

  create-release:
    name: "Create release"
    runs-on: "ubuntu-latest"
    needs: Build

    steps:
      # ...
      - uses: actions/download-artifact@v3
        with:
          name: vault-snapshot

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            vault-snapshot
